/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.reply.liferay.exercise.model.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.reply.liferay.exercise.model.model.FuelPump;
import com.reply.liferay.exercise.model.model.FuelPumpModel;
import com.reply.liferay.exercise.model.model.FuelPumpSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the FuelPump service. Represents a row in the &quot;GB_FuelPump&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.reply.liferay.exercise.model.model.FuelPumpModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FuelPumpImpl}.
 * </p>
 *
 * @author s.girardello
 * @see FuelPumpImpl
 * @see com.reply.liferay.exercise.model.model.FuelPump
 * @see com.reply.liferay.exercise.model.model.FuelPumpModel
 * @generated
 */
@JSON(strict = true)
public class FuelPumpModelImpl extends BaseModelImpl<FuelPump>
	implements FuelPumpModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a fuel pump model instance should use the {@link com.reply.liferay.exercise.model.model.FuelPump} interface instead.
	 */
	public static final String TABLE_NAME = "GB_FuelPump";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "fuelPumpId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "gasolineCapacity", Types.INTEGER },
			{ "dieselCapacity", Types.INTEGER },
			{ "cashInserted", Types.INTEGER },
			{ "inactivityTime", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table GB_FuelPump (uuid_ VARCHAR(75) null,fuelPumpId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,gasolineCapacity INTEGER,dieselCapacity INTEGER,cashInserted INTEGER,inactivityTime INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table GB_FuelPump";
	public static final String ORDER_BY_JPQL = " ORDER BY fuelPump.createDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY GB_FuelPump.createDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.reply.liferay.exercise.model.model.FuelPump"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.reply.liferay.exercise.model.model.FuelPump"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.reply.liferay.exercise.model.model.FuelPump"),
			true);
	public static long COMPANYID_COLUMN_BITMASK = 1L;
	public static long GROUPID_COLUMN_BITMASK = 2L;
	public static long UUID_COLUMN_BITMASK = 4L;
	public static long CREATEDATE_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static FuelPump toModel(FuelPumpSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		FuelPump model = new FuelPumpImpl();

		model.setUuid(soapModel.getUuid());
		model.setFuelPumpId(soapModel.getFuelPumpId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setGasolineCapacity(soapModel.getGasolineCapacity());
		model.setDieselCapacity(soapModel.getDieselCapacity());
		model.setCashInserted(soapModel.getCashInserted());
		model.setInactivityTime(soapModel.getInactivityTime());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<FuelPump> toModels(FuelPumpSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<FuelPump> models = new ArrayList<FuelPump>(soapModels.length);

		for (FuelPumpSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.reply.liferay.exercise.model.model.FuelPump"));

	public FuelPumpModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _fuelPumpId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFuelPumpId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _fuelPumpId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FuelPump.class;
	}

	@Override
	public String getModelClassName() {
		return FuelPump.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("fuelPumpId", getFuelPumpId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("gasolineCapacity", getGasolineCapacity());
		attributes.put("dieselCapacity", getDieselCapacity());
		attributes.put("cashInserted", getCashInserted());
		attributes.put("inactivityTime", getInactivityTime());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long fuelPumpId = (Long)attributes.get("fuelPumpId");

		if (fuelPumpId != null) {
			setFuelPumpId(fuelPumpId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Integer gasolineCapacity = (Integer)attributes.get("gasolineCapacity");

		if (gasolineCapacity != null) {
			setGasolineCapacity(gasolineCapacity);
		}

		Integer dieselCapacity = (Integer)attributes.get("dieselCapacity");

		if (dieselCapacity != null) {
			setDieselCapacity(dieselCapacity);
		}

		Integer cashInserted = (Integer)attributes.get("cashInserted");

		if (cashInserted != null) {
			setCashInserted(cashInserted);
		}

		Integer inactivityTime = (Integer)attributes.get("inactivityTime");

		if (inactivityTime != null) {
			setInactivityTime(inactivityTime);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getFuelPumpId() {
		return _fuelPumpId;
	}

	@Override
	public void setFuelPumpId(long fuelPumpId) {
		_fuelPumpId = fuelPumpId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getGasolineCapacity() {
		return _gasolineCapacity;
	}

	@Override
	public void setGasolineCapacity(int gasolineCapacity) {
		_gasolineCapacity = gasolineCapacity;
	}

	@JSON
	@Override
	public int getDieselCapacity() {
		return _dieselCapacity;
	}

	@Override
	public void setDieselCapacity(int dieselCapacity) {
		_dieselCapacity = dieselCapacity;
	}

	@JSON
	@Override
	public int getCashInserted() {
		return _cashInserted;
	}

	@Override
	public void setCashInserted(int cashInserted) {
		_cashInserted = cashInserted;
	}

	@JSON
	@Override
	public int getInactivityTime() {
		return _inactivityTime;
	}

	@Override
	public void setInactivityTime(int inactivityTime) {
		_inactivityTime = inactivityTime;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				FuelPump.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			FuelPump.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FuelPump toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (FuelPump)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FuelPumpImpl fuelPumpImpl = new FuelPumpImpl();

		fuelPumpImpl.setUuid(getUuid());
		fuelPumpImpl.setFuelPumpId(getFuelPumpId());
		fuelPumpImpl.setGroupId(getGroupId());
		fuelPumpImpl.setCompanyId(getCompanyId());
		fuelPumpImpl.setUserId(getUserId());
		fuelPumpImpl.setUserName(getUserName());
		fuelPumpImpl.setCreateDate(getCreateDate());
		fuelPumpImpl.setModifiedDate(getModifiedDate());
		fuelPumpImpl.setGasolineCapacity(getGasolineCapacity());
		fuelPumpImpl.setDieselCapacity(getDieselCapacity());
		fuelPumpImpl.setCashInserted(getCashInserted());
		fuelPumpImpl.setInactivityTime(getInactivityTime());

		fuelPumpImpl.resetOriginalValues();

		return fuelPumpImpl;
	}

	@Override
	public int compareTo(FuelPump fuelPump) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(), fuelPump.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof FuelPump)) {
			return false;
		}

		FuelPump fuelPump = (FuelPump)obj;

		long primaryKey = fuelPump.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		FuelPumpModelImpl fuelPumpModelImpl = this;

		fuelPumpModelImpl._originalUuid = fuelPumpModelImpl._uuid;

		fuelPumpModelImpl._originalGroupId = fuelPumpModelImpl._groupId;

		fuelPumpModelImpl._setOriginalGroupId = false;

		fuelPumpModelImpl._originalCompanyId = fuelPumpModelImpl._companyId;

		fuelPumpModelImpl._setOriginalCompanyId = false;

		fuelPumpModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<FuelPump> toCacheModel() {
		FuelPumpCacheModel fuelPumpCacheModel = new FuelPumpCacheModel();

		fuelPumpCacheModel.uuid = getUuid();

		String uuid = fuelPumpCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			fuelPumpCacheModel.uuid = null;
		}

		fuelPumpCacheModel.fuelPumpId = getFuelPumpId();

		fuelPumpCacheModel.groupId = getGroupId();

		fuelPumpCacheModel.companyId = getCompanyId();

		fuelPumpCacheModel.userId = getUserId();

		fuelPumpCacheModel.userName = getUserName();

		String userName = fuelPumpCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			fuelPumpCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			fuelPumpCacheModel.createDate = createDate.getTime();
		}
		else {
			fuelPumpCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			fuelPumpCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			fuelPumpCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		fuelPumpCacheModel.gasolineCapacity = getGasolineCapacity();

		fuelPumpCacheModel.dieselCapacity = getDieselCapacity();

		fuelPumpCacheModel.cashInserted = getCashInserted();

		fuelPumpCacheModel.inactivityTime = getInactivityTime();

		return fuelPumpCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", fuelPumpId=");
		sb.append(getFuelPumpId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", gasolineCapacity=");
		sb.append(getGasolineCapacity());
		sb.append(", dieselCapacity=");
		sb.append(getDieselCapacity());
		sb.append(", cashInserted=");
		sb.append(getCashInserted());
		sb.append(", inactivityTime=");
		sb.append(getInactivityTime());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append("com.reply.liferay.exercise.model.model.FuelPump");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fuelPumpId</column-name><column-value><![CDATA[");
		sb.append(getFuelPumpId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gasolineCapacity</column-name><column-value><![CDATA[");
		sb.append(getGasolineCapacity());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dieselCapacity</column-name><column-value><![CDATA[");
		sb.append(getDieselCapacity());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cashInserted</column-name><column-value><![CDATA[");
		sb.append(getCashInserted());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>inactivityTime</column-name><column-value><![CDATA[");
		sb.append(getInactivityTime());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = FuelPump.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			FuelPump.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _fuelPumpId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private int _gasolineCapacity;
	private int _dieselCapacity;
	private int _cashInserted;
	private int _inactivityTime;
	private long _columnBitmask;
	private FuelPump _escapedModel;
}