/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.reply.liferay.exercise.model.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.reply.liferay.exercise.model.model.Rifornimento;
import com.reply.liferay.exercise.model.model.RifornimentoModel;
import com.reply.liferay.exercise.model.model.RifornimentoSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Rifornimento service. Represents a row in the &quot;SG_Rifornimento&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.reply.liferay.exercise.model.model.RifornimentoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RifornimentoImpl}.
 * </p>
 *
 * @author s.girardello
 * @see RifornimentoImpl
 * @see com.reply.liferay.exercise.model.model.Rifornimento
 * @see com.reply.liferay.exercise.model.model.RifornimentoModel
 * @generated
 */
@JSON(strict = true)
public class RifornimentoModelImpl extends BaseModelImpl<Rifornimento>
	implements RifornimentoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a rifornimento model instance should use the {@link com.reply.liferay.exercise.model.model.Rifornimento} interface instead.
	 */
	public static final String TABLE_NAME = "SG_Rifornimento";
	public static final Object[][] TABLE_COLUMNS = {
			{ "rifornimentoId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "tipoCarburante", Types.VARCHAR },
			{ "denaroInserito", Types.INTEGER },
			{ "pompaId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table SG_Rifornimento (rifornimentoId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,tipoCarburante VARCHAR(75) null,denaroInserito INTEGER,pompaId LONG)";
	public static final String TABLE_SQL_DROP = "drop table SG_Rifornimento";
	public static final String ORDER_BY_JPQL = " ORDER BY rifornimento.rifornimentoId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY SG_Rifornimento.rifornimentoId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.reply.liferay.exercise.model.model.Rifornimento"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.reply.liferay.exercise.model.model.Rifornimento"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Rifornimento toModel(RifornimentoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Rifornimento model = new RifornimentoImpl();

		model.setRifornimentoId(soapModel.getRifornimentoId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setTipoCarburante(soapModel.getTipoCarburante());
		model.setDenaroInserito(soapModel.getDenaroInserito());
		model.setPompaId(soapModel.getPompaId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Rifornimento> toModels(RifornimentoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Rifornimento> models = new ArrayList<Rifornimento>(soapModels.length);

		for (RifornimentoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.reply.liferay.exercise.model.model.Rifornimento"));

	public RifornimentoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _rifornimentoId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setRifornimentoId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _rifornimentoId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Rifornimento.class;
	}

	@Override
	public String getModelClassName() {
		return Rifornimento.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("rifornimentoId", getRifornimentoId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("tipoCarburante", getTipoCarburante());
		attributes.put("denaroInserito", getDenaroInserito());
		attributes.put("pompaId", getPompaId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long rifornimentoId = (Long)attributes.get("rifornimentoId");

		if (rifornimentoId != null) {
			setRifornimentoId(rifornimentoId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String tipoCarburante = (String)attributes.get("tipoCarburante");

		if (tipoCarburante != null) {
			setTipoCarburante(tipoCarburante);
		}

		Integer denaroInserito = (Integer)attributes.get("denaroInserito");

		if (denaroInserito != null) {
			setDenaroInserito(denaroInserito);
		}

		Long pompaId = (Long)attributes.get("pompaId");

		if (pompaId != null) {
			setPompaId(pompaId);
		}
	}

	@JSON
	@Override
	public long getRifornimentoId() {
		return _rifornimentoId;
	}

	@Override
	public void setRifornimentoId(long rifornimentoId) {
		_rifornimentoId = rifornimentoId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getTipoCarburante() {
		if (_tipoCarburante == null) {
			return StringPool.BLANK;
		}
		else {
			return _tipoCarburante;
		}
	}

	@Override
	public void setTipoCarburante(String tipoCarburante) {
		_tipoCarburante = tipoCarburante;
	}

	@JSON
	@Override
	public int getDenaroInserito() {
		return _denaroInserito;
	}

	@Override
	public void setDenaroInserito(int denaroInserito) {
		_denaroInserito = denaroInserito;
	}

	@JSON
	@Override
	public long getPompaId() {
		return _pompaId;
	}

	@Override
	public void setPompaId(long pompaId) {
		_pompaId = pompaId;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Rifornimento.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Rifornimento toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Rifornimento)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RifornimentoImpl rifornimentoImpl = new RifornimentoImpl();

		rifornimentoImpl.setRifornimentoId(getRifornimentoId());
		rifornimentoImpl.setGroupId(getGroupId());
		rifornimentoImpl.setCompanyId(getCompanyId());
		rifornimentoImpl.setUserId(getUserId());
		rifornimentoImpl.setUserName(getUserName());
		rifornimentoImpl.setCreateDate(getCreateDate());
		rifornimentoImpl.setModifiedDate(getModifiedDate());
		rifornimentoImpl.setTipoCarburante(getTipoCarburante());
		rifornimentoImpl.setDenaroInserito(getDenaroInserito());
		rifornimentoImpl.setPompaId(getPompaId());

		rifornimentoImpl.resetOriginalValues();

		return rifornimentoImpl;
	}

	@Override
	public int compareTo(Rifornimento rifornimento) {
		long primaryKey = rifornimento.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Rifornimento)) {
			return false;
		}

		Rifornimento rifornimento = (Rifornimento)obj;

		long primaryKey = rifornimento.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Rifornimento> toCacheModel() {
		RifornimentoCacheModel rifornimentoCacheModel = new RifornimentoCacheModel();

		rifornimentoCacheModel.rifornimentoId = getRifornimentoId();

		rifornimentoCacheModel.groupId = getGroupId();

		rifornimentoCacheModel.companyId = getCompanyId();

		rifornimentoCacheModel.userId = getUserId();

		rifornimentoCacheModel.userName = getUserName();

		String userName = rifornimentoCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			rifornimentoCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			rifornimentoCacheModel.createDate = createDate.getTime();
		}
		else {
			rifornimentoCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			rifornimentoCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			rifornimentoCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		rifornimentoCacheModel.tipoCarburante = getTipoCarburante();

		String tipoCarburante = rifornimentoCacheModel.tipoCarburante;

		if ((tipoCarburante != null) && (tipoCarburante.length() == 0)) {
			rifornimentoCacheModel.tipoCarburante = null;
		}

		rifornimentoCacheModel.denaroInserito = getDenaroInserito();

		rifornimentoCacheModel.pompaId = getPompaId();

		return rifornimentoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{rifornimentoId=");
		sb.append(getRifornimentoId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", tipoCarburante=");
		sb.append(getTipoCarburante());
		sb.append(", denaroInserito=");
		sb.append(getDenaroInserito());
		sb.append(", pompaId=");
		sb.append(getPompaId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("com.reply.liferay.exercise.model.model.Rifornimento");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>rifornimentoId</column-name><column-value><![CDATA[");
		sb.append(getRifornimentoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tipoCarburante</column-name><column-value><![CDATA[");
		sb.append(getTipoCarburante());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>denaroInserito</column-name><column-value><![CDATA[");
		sb.append(getDenaroInserito());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>pompaId</column-name><column-value><![CDATA[");
		sb.append(getPompaId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Rifornimento.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			Rifornimento.class
		};
	private long _rifornimentoId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _tipoCarburante;
	private int _denaroInserito;
	private long _pompaId;
	private Rifornimento _escapedModel;
}