/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.reply.liferay.exercise.model.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Pompa service. Represents a row in the &quot;SG_Pompa&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.reply.liferay.exercise.model.model.impl.PompaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.reply.liferay.exercise.model.model.impl.PompaImpl}.
 * </p>
 *
 * @author s.girardello
 * @see Pompa
 * @see com.reply.liferay.exercise.model.model.impl.PompaImpl
 * @see com.reply.liferay.exercise.model.model.impl.PompaModelImpl
 * @generated
 */
public interface PompaModel extends BaseModel<Pompa>, StagedGroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a pompa model instance should use the {@link Pompa} interface instead.
	 */

	/**
	 * Returns the primary key of this pompa.
	 *
	 * @return the primary key of this pompa
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this pompa.
	 *
	 * @param primaryKey the primary key of this pompa
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this pompa.
	 *
	 * @return the uuid of this pompa
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this pompa.
	 *
	 * @param uuid the uuid of this pompa
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the pompa ID of this pompa.
	 *
	 * @return the pompa ID of this pompa
	 */
	public long getPompaId();

	/**
	 * Sets the pompa ID of this pompa.
	 *
	 * @param pompaId the pompa ID of this pompa
	 */
	public void setPompaId(long pompaId);

	/**
	 * Returns the group ID of this pompa.
	 *
	 * @return the group ID of this pompa
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this pompa.
	 *
	 * @param groupId the group ID of this pompa
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this pompa.
	 *
	 * @return the company ID of this pompa
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this pompa.
	 *
	 * @param companyId the company ID of this pompa
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this pompa.
	 *
	 * @return the user ID of this pompa
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this pompa.
	 *
	 * @param userId the user ID of this pompa
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this pompa.
	 *
	 * @return the user uuid of this pompa
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this pompa.
	 *
	 * @param userUuid the user uuid of this pompa
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this pompa.
	 *
	 * @return the user name of this pompa
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this pompa.
	 *
	 * @param userName the user name of this pompa
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this pompa.
	 *
	 * @return the create date of this pompa
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this pompa.
	 *
	 * @param createDate the create date of this pompa
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this pompa.
	 *
	 * @return the modified date of this pompa
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this pompa.
	 *
	 * @param modifiedDate the modified date of this pompa
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the quantita diesel of this pompa.
	 *
	 * @return the quantita diesel of this pompa
	 */
	public int getQuantitaDiesel();

	/**
	 * Sets the quantita diesel of this pompa.
	 *
	 * @param quantitaDiesel the quantita diesel of this pompa
	 */
	public void setQuantitaDiesel(int quantitaDiesel);

	/**
	 * Returns the quantita benzina of this pompa.
	 *
	 * @return the quantita benzina of this pompa
	 */
	public int getQuantitaBenzina();

	/**
	 * Sets the quantita benzina of this pompa.
	 *
	 * @param quantitaBenzina the quantita benzina of this pompa
	 */
	public void setQuantitaBenzina(int quantitaBenzina);

	/**
	 * Returns the tempo giacenza of this pompa.
	 *
	 * @return the tempo giacenza of this pompa
	 */
	public int getTempoGiacenza();

	/**
	 * Sets the tempo giacenza of this pompa.
	 *
	 * @param tempoGiacenza the tempo giacenza of this pompa
	 */
	public void setTempoGiacenza(int tempoGiacenza);

	/**
	 * Returns the incasso totale pompa of this pompa.
	 *
	 * @return the incasso totale pompa of this pompa
	 */
	public int getIncassoTotalePompa();

	/**
	 * Sets the incasso totale pompa of this pompa.
	 *
	 * @param incassoTotalePompa the incasso totale pompa of this pompa
	 */
	public void setIncassoTotalePompa(int incassoTotalePompa);

	/**
	 * Returns the stato pompa of this pompa.
	 *
	 * @return the stato pompa of this pompa
	 */
	public boolean getStatoPompa();

	/**
	 * Returns <code>true</code> if this pompa is stato pompa.
	 *
	 * @return <code>true</code> if this pompa is stato pompa; <code>false</code> otherwise
	 */
	public boolean isStatoPompa();

	/**
	 * Sets whether this pompa is stato pompa.
	 *
	 * @param statoPompa the stato pompa of this pompa
	 */
	public void setStatoPompa(boolean statoPompa);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.reply.liferay.exercise.model.model.Pompa pompa);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.reply.liferay.exercise.model.model.Pompa> toCacheModel();

	@Override
	public com.reply.liferay.exercise.model.model.Pompa toEscapedModel();

	@Override
	public com.reply.liferay.exercise.model.model.Pompa toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}